"""Constants for GIOS integration."""
ATTR_AQI = "AQI"
ATTR_INDEX = "index"
ATTR_NAME = "name"
ATTR_STATION = "station"
ATTR_VALUE = "value"
CONF_STATION_ID = "station_id"
DATA_CLIENT = "client"
DEFAULT_NAME = "GIOŚ"
DEFAULT_SCAN_INTERVAL = 1800
DOMAIN = "gios"
